// <auto-generated />
using System;
using FinalProjectGroup11.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectGroup11.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20251203215036_MoviesList")]
    partial class MoviesList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectGroup11.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Name = "Django Unchained",
                            Rating = 5,
                            Year = 2012
                        },
                        new
                        {
                            MovieId = 2,
                            Name = "Spider-Man: Across the Spider-Verse",
                            Rating = 4,
                            Year = 2023
                        },
                        new
                        {
                            MovieId = 3,
                            Name = "Predator Killer of Killers",
                            Rating = 5,
                            Year = 2025
                        },
                        new
                        {
                            MovieId = 4,
                            Name = "Baby Driver",
                            Rating = 4,
                            Year = 2017
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
